services:
  # 1. SERVIDOR WEB (NGINX)
  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_nginx
    restart: unless-stopped
    ports:
      - "8080:80"   # HTTP
      - "8443:443"  # HTTPS
    volumes:
      - ./:/var/www/html
      - ./.podman/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - php

  # 2. INTÃ‰RPRETE PHP (FPM)
  php:
    build: .
    image: localhost/${PROJECT_NAME}_php_fpm:latest
    container_name: ${PROJECT_NAME}_php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html

networks:
  default:
    name: ${PROJECT_NAME}_network
