services:
  # 1. SERVIDOR WEB (NGINX)
  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_nginx
    restart: unless-stopped
    network_mode: service:php
    volumes:
      - ./:/var/www/html:Z
      - ./.podman/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:Z
    depends_on:
      - php

  # 2. INTÃ‰RPRETE PHP (FPM)
  php:
    build: .
    image: localhost/${PROJECT_NAME}_php_fpm:latest
    container_name: ${PROJECT_NAME}_php
    restart: unless-stopped
    ports:
      - "8080:8080"  # HTTP
      - "8443:8443"  # HTTPS
    volumes:
      - ./:/var/www/html:Z

networks:
  default:
    name: ${PROJECT_NAME}_network
