services:
  # 1. SERVIDOR WEB (NGINX)
  nginx:
    image: nginx:alpine
    container_name: whatever_nginx
    ports:
      - "8080:80"   # HTTP
      - "8443:443"  # HTTPS
    volumes:
      - ./:/var/www/html
      - ./.podman/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - php

  # 2. INTÃ‰RPRETE PHP (FPM)
  php:
    build: .
    image: localhost/tnp_php_fpm:latest
    container_name: tnp_php
    volumes:
      - ./:/var/www/html
